# **NumPy Basics**


## **Creating a Basic Array**


In [1]:
   import numpy as np
   arr1=np.array([1,2,3])
   arr2=np.array(['a','b','c','d','e'])
   arr3= np.array((1, 2, 3, 4, 5)) # You can also pass a tuple to creat an Array
   print(arr1)
   print(arr2)
   print(arr3)
   print(type(arr1))

[1 2 3]
['a' 'b' 'c' 'd' 'e']
[1 2 3 4 5]
<class 'numpy.ndarray'>


Arrays using ***np.zeros(), np.ones(), np.arange()***

In [2]:
   import numpy as np
   a=np.zeros(3)
   b=np.ones(5)
   c=np.arange(10)
   d=np.arange(2,9)   # To specify start and stop
   e=np.arange(1,10,2) # To specify start and stop with step size
   print(a)
   print(b)
   print(c)
   print(d)
   print(e)

[0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]
[1 3 5 7 9]


## **NdArray (N-Dimensional Array)**

 **A 2-Dimensional Array**

In [5]:
   import numpy as np
   arr1=np.array([[1,2,3],[4,5,6]])
   arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
   arr3=np.array([['a','b','c'],['d','e','f']])
   
   #creates a 3X3 array with all zeros
   zeros=np.zeros((3,3))
   
   #creates a 2X2 array with all ones
   ones=np.ones((2,2),dtype='int64')  #specify the type with (dtype) parameter 
   
   print(arr1)
   print(arr2)
   print(arr3)
   print(zeros)
   print(ones)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[['a' 'b' 'c']
 ['d' 'e' 'f']]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]]


NumPy provides some cool methods you can check the number of dimensions using ***ndim***

In [6]:
   import numpy as np

   a = np.array(42)
   b = np.array([1, 2, 3, 4, 5])
   c = np.array([[1, 2, 3], [4, 5, 6]])
   d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

   print(a.ndim)
   print(b.ndim)
   print(c.ndim)
   print(d.ndim)

0
1
2
3


**Basic Operations with Arrays**

In [7]:
   import numpy as np
   arr1=np.array([5,5,5,5])
   arr2=np.array([3,3,3,3])
   c=arr1+arr2
   d=arr1-arr2
   e=arr1/arr2
   print(arr1)
   print(arr2)
   print(c) # addition
   print(d) # subtraction
   print(e) # division
   print("Adding one to all elements:",c+1)
   print("Subtracting one from all elements:",d-1)

[5 5 5 5]
[3 3 3 3]
[8 8 8 8]
[2 2 2 2]
[1.66666667 1.66666667 1.66666667 1.66666667]
Adding one to all elements: [9 9 9 9]
Subtracting one from all elements: [1 1 1 1]


## **Array Indexing and Slicing**

### **Array Indexing**

In [9]:
   import numpy as np
   arr1= np.array([3,2,3,4])
   arr2= np.array([2,1,1,3])
   arr3= np.array(['D','e','V','I','n','c','e','p','t'])
   arr4= np.array([[1,2,3,4,5], [6,7,8,9,10]])
   print(arr1[0]) # prints first element
   print(arr1[-1]) # prints last element
   print(arr2[2]) # prints third element
   print(arr3[0]) # prints first element
   print(arr4[1][3]) #prints 9
   print(arr4[1,3]) # Or you can use this type 

3
4
1
D
9
9


### **Array Slicing**

In [10]:
   import numpy as np
   arr1=np.array(['D','e','V','I','n','c','e','p','t'])
   arr2=np.array([1,2,3,4,5,6,7,8,9])
   
   #2-D Slicing
   arr3=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
   
   print(arr1[:3]) # default is taken as 0
   print(arr1[0:3])
   print(arr1[3:]) # taken till the end
   print(arr1[::2])
   
   print(arr2[-4:-1])
   print(arr2[::2]) # step size as 2
   
   # 2-D Slicing
   print(arr3[1,1:4])
   print(arr3[0:2, 2])
   print(arr3[0:2, 1:4])

['D' 'e' 'V']
['D' 'e' 'V']
['I' 'n' 'c' 'e' 'p' 't']
['D' 'V' 'n' 'e' 't']
[6 7 8]
[1 3 5 7 9]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


**All in One Example**

In [11]:
   import numpy as np
   data = np.array([1, 2, 3])
   print(data[1])
   print(data[0:2])
   print(data[1:])
   print(data[-2:])

2
[1 2]
[2 3]
[2 3]
