# **Numpy Functions**

## **NumPy Array Shape**

In [12]:
   import numpy as np
   arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
   arr1= np.array([1,2,3,4])

   print(arr.shape)
   print(arr1.shape)

(2, 4)
(4,)


**All in One Example**

In [16]:
   array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])
 
   print('No of dimensions of the array:',array_example.ndim)     # .ndim for dimensions
   print('Total no of elements of the array:',array_example.size) # .size for size
   print('Shape of the array:',array_example.shape)                # .shape for shape

No of dimensions of the array: 3
Total no of elements of the array: 24
Shape of the array: (3, 2, 4)


## **NumPy Array Reshaping**

**Reshape from 1-Dimensional to 2-Dimensional**

In [17]:
   import numpy as np
   arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
   newarr1 = arr1.reshape(4, 3)
   arr2 = np.array(['D','e','V','I','n','c','e','p','t'])
   newarr2 = arr2.reshape(3,3)
   print(newarr1)
   print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[['D' 'e' 'V']
 ['I' 'n' 'c']
 ['e' 'p' 't']]


**Reshape from 1-Dimensional to 3-Dimensional**

In [18]:
   import numpy as np
   arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
   newarr = arr.reshape(2, 3, 2)
   print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Multi-Dimensional Array into 1-Dimensional Array**

In [19]:
   import numpy as np
   arr = np.array([[1, 2, 3], [4, 5, 6]])
   newarr = arr.reshape(-1)
   print(newarr)

[1 2 3 4 5 6]


## **NumPy Sorting and Searching**

### **NumPy Sorting**

In [20]:
   import numpy as np
   arr1 = np.array([3, 2, 0, 1])
   arr2 = np.array(['red','blue','green'])
   
   # 2-D array
   arr3 = np.array([[3, 2, 4], [5, 0, 1]])
   
   print(np.sort(arr1))
   print(np.sort(arr2))
   print(np.sort(arr3))

[0 1 2 3]
['blue' 'green' 'red']
[[2 3 4]
 [0 1 5]]


### **NumPy Searching**

**where() :**

In [21]:
   import numpy as np
   arr1 = np.array([1, 2, 3, 4, 5, 4, 4])
   x = np.where(arr1 == 4)
   y = np.where(arr1%2 == 0)
   z = np.where(arr1%2 == 1)
   print(x)
   print(y)
   print(z)

(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)
(array([0, 2, 4]),)


**searchsorted() :**

In [22]:
   import numpy as np
   arr1 = np.array([6, 7, 8, 9])
   x = np.searchsorted(arr1, 7)
   print(x)
   
   # Multiple values
   arr2 = np.array([1, 3, 5, 7])
   y = np.searchsorted(arr2, [2, 4, 6])
   print(y)

1
[1 2 3]


## **Mean, Median, Mode**

### **Mean**

In [23]:
   import numpy as np
   arr=np.array([19,13,18,21,44,17,12,31,37,8,12,27])
   x=np.mean(arr)
   print(x)

21.583333333333332


### **Median**

In [24]:
   import numpy
   # For one value in the middle
   speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]
   x = numpy.median(speed)
   print(x)
   
   # For two values in the middle
   speed1 = [99,86,87,88,86,103,87,94,78,77,85,86]
   y = numpy.median(speed1)
   print(y)

87.0
86.5


### **Mode**

In [25]:
   from scipy import stats
   speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]
   x = stats.mode(speed)
   print(x)

ModeResult(mode=array([86]), count=array([3]))


## **Standard Deviation (σ)**

In [26]:
   import numpy
   speed = [86,87,88,86,87,85,86]
   x = numpy.std(speed)
   print(x)
   
   speed1 = [32,111,138,28,59,77,97]
   y = numpy.std(speed1)
   print(y)

0.9035079029052513
37.84501153334721


# **Practice all you want and play with the code as much as you want..**
